[project]
site_name = "repotainer"
site_description = "Add your description here"
repo_name = "suchi-pragya/repotainer"
repo_url = "https://github.com/suchi-pragya/repotainer"
site_author = "Suchi Pragya"
copyright = "Copyright &copy; 2026 Suchi Pragya"
nav = [
  { Home = "index.md" },
  { Contributing = "contributing/index.md" },
]

[project.theme]
language = "en"
features = [
  "announce.dismiss",
  "content.action.edit",
  "content.action.view",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.instant.progress",
  "navigation.path",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
]

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
scheme = "default"
media = "(prefers-color-scheme: light)"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
scheme = "slate"
media = "(prefers-color-scheme: dark)"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.icon]
logo = "lucide/layout-template"
next = "lucide/arrow-right"
previous = "lucide/arrow-left"
search = "lucide/search"
top = "lucide/arrow-up"
edit = "lucide/file-pen-line"
view = "lucide/file-braces-corner"

[project.markdown_extensions.admonition]

[project.markdown_extensions.pymdownx.details]

[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" },
]

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
